import * as dotenv from "dotenv";
dotenv.config();
export const PORT = process.env.PORT || "8080";
export const ENVIRONMENT = process.env.NODE_ENV || "";
export const APP_URL = process.env.APP_URL || "";
export const APP_URL_REMOTE = process.env.APP_URL_REMOTE || "";
export const BASE_PATH = process.env.BASE_PATH || "";
export const DB_NAME = process.env.DB_NAME || "billondb";
export const DB_USER = process.env.DB_USER || "root";
export const DB_PASSWORD = process.env.DB_PASSWORD || "";
export const DB_HOST = process.env.DB_HOST || "localhost";
export const JWT_SECRET = process.env.JWT_SECRET || "somesuperbillonkey";
export const AWS_ACCESS_KEY = process.env.AWS_ACCESS_KEY || "";
export const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || "";
export const S3_REGION = process.env.S3_REGION || "";
export const S3_BUCKET = process.env.S3_BUCKET || "";
export const EMAIL_USERNAME = process.env.EMAIL_USERNAME || "";
export const EMAIL_PASSWORD = process.env.EMAIL_PASSWORD || "";
export const BILLON_BASE_URL = process.env.BILLON_BASE_URL || "";
export const OKRA_TOKEN = process.env.OKRA_TOKEN || "";
export const SMTP_USERNAME = process.env.SMTP_USERNAME || "";
export const SMTP_PASSWORD = process.env.SMTP_PASSWORD || "";
export const IP_INTEGRATED_URL = process.env.IP_INTEGRATED_URL || "";
export const ONE_SIGNAL_APP_ID = process.env.ONE_SIGNAL_APP_ID || "";
export const ONE_SIGNAL_APP_URL = process.env.ONE_SIGNAL_APP_URL || "";
export const ONE_SIGNAL_NOTIFICATION_URL = process.env.ONE_SIGNAL_NOTIFICATION_URL || "";
export const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY || "";
export const IP_INTEGRATED_USERNAME = process.env.IP_INTEGRATED_USERNAME || "";
export const IP_INTEGRATED_PASSWORD = process.env.IP_INTEGRATED_PASSWORD || "";

